[tool.poetry]
name = "mapmallow"
version = "2.0.0"
description = "Set of mapping functions that will map according to a configuration file and do validation with marshmallow"
authors = ["Thomas Borgen <thomas.borgen@greenbird.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.6"
typing_extensions = "3.7.4"
pycountry = "19.8.18"
returns = "^0.14.0"
jsonschema = "^3.2.0"

[tool.poetry.dev-dependencies]
mypy = "^0.782"
wemake-python-styleguide = "^0.14.1"
pre-commit = "^1.18"
simplejson = "^3.16"

safety = "^1.8"

pytest = "^5.2"
pytest-cov = "^2.8"
coverage-badge = "^1.0"
tomlkit = "^0.5.8"
mkdocs-material = "^5.5.7"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
